-- ============================================================================
-- Tasty Bytes Cortex Analyst - Semantic View Creation
-- ============================================================================
-- This script creates a semantic view for the Tasty Bytes customer loyalty
-- metrics dataset, enabling natural language queries via Cortex Analyst.
--
-- Prerequisites:
-- 1. TASTY_BYTES database must be created and populated
--    (Run load_tasty_bytes_data.sql first)
-- 2. ACCOUNTADMIN role or equivalent permissions
-- 3. Cortex Analyst feature enabled in your Snowflake account
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE TASTY_BYTES;
USE SCHEMA HARMONIZED;

-- ============================================================================
-- Step 1: Verify the base view exists
-- ============================================================================

SHOW VIEWS LIKE 'CUSTOMER_LOYALTY_METRICS_V' IN SCHEMA TASTY_BYTES.HARMONIZED;

-- You should see the CUSTOMER_LOYALTY_METRICS_V view
-- If not, run load_tasty_bytes_data.sql first

-- ============================================================================
-- Step 2: Create the Semantic View from YAML
-- ============================================================================

-- This stored procedure creates a semantic view from a YAML specification
-- The YAML defines:
-- - Business-friendly names and descriptions
-- - Dimensions (attributes for filtering and grouping)
-- - Facts/Metrics (measurable values)
-- - Verified queries (pre-tested question/SQL pairs)
-- - Custom instructions for SQL generation

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
  'TASTY_BYTES.HARMONIZED',
  $$
name: HARMONIZEDCUSTOMERMETRICSSEMANTICVIEW
description: Semantic View to answer questions on Tasty Bytes customer metrics
tables:
  - name: CUSTOMER_LOYALTY_METRICS_V
    description: This view provides a comprehensive overview of customer loyalty metrics, including customer demographics, total sales, and a list of unique locations visited by each customer, enabling analysis of customer behavior and loyalty program effectiveness.
    base_table:
      database: TASTY_BYTES
      schema: HARMONIZED
      table: CUSTOMER_LOYALTY_METRICS_V
    dimensions:
      - name: CITY
        description: The city where the customer is located.
        expr: CITY
        data_type: VARCHAR(16777216)
        sample_values:
          - Boston
          - Mumbai
          - Cairo
      - name: COUNTRY
        description: The country where the customer is located.
        expr: COUNTRY
        data_type: VARCHAR(16777216)
        sample_values:
          - Egypt
          - India
          - United States
      - name: CUSTOMER_ID
        description: Unique identifier for a customer in the loyalty program.
        expr: CUSTOMER_ID
        data_type: NUMBER(38,0)
        sample_values:
          - '110913'
          - '130576'
          - '90298'
      - name: E_MAIL
        description: The email address of the customer.
        expr: E_MAIL
        data_type: VARCHAR(16777216)
        sample_values:
          - Anna.Sanchez@hotmail.com
          - Grace.Kline@hotmail.com
          - Dahlia.Buchanan@ymail.com
      - name: FIRST_NAME
        description: The first name of the customer.
        expr: FIRST_NAME
        data_type: VARCHAR(16777216)
        sample_values:
          - Thaddeus
          - Deshawn
          - Madelynn
      - name: LAST_NAME
        description: The customer's last name.
        expr: LAST_NAME
        data_type: VARCHAR(16777216)
        sample_values:
          - Baker
          - Allison
          - Farmer
      - name: PHONE_NUMBER
        description: The phone number associated with a customer's loyalty program account.
        expr: PHONE_NUMBER
        data_type: VARCHAR(16777216)
        sample_values:
          - 131-847-6052
          - 642-785-8671
          - 606-217-4474
      - name: VISITED_LOCATION_IDS_ARRAY
        description: Array of unique location IDs visited by a customer.
        expr: VISITED_LOCATION_IDS_ARRAY
        data_type: ARRAY
    facts:
      - name: TOTAL_SALES
        description: The total sales amount generated by each customer.
        expr: TOTAL_SALES
        data_type: NUMBER(38,4)
        access_modifier: public_access
        sample_values:
          - '1745.7500'
          - '2809.5000'
          - '3302.0000'
verified_queries:
  - name: How many unique customers are tracked in our loyalty program?
    question: How many unique customers are tracked in our loyalty program?
    sql: |-
      SELECT
        COUNT(DISTINCT customer_id)
      FROM
        customer_loyalty_metrics_v
    use_as_onboarding_question: false
    verified_by: Aaman Lamba
    verified_at: 1764945263
  - name: Which countries generate the least to most total sales revenue?
    question: Which countries generate the least to most total sales revenue?
    sql: |-
      SELECT
        country,
        SUM(total_sales)
      FROM
        customer_loyalty_metrics_v
      GROUP BY
        country
      ORDER BY
        SUM(total_sales)
    use_as_onboarding_question: false
    verified_by: Aaman Lamba
    verified_at: 1764945276
  - name: Which countries have the highest number of customers in our loyalty program?
    question: Which countries have the highest number of customers in our loyalty program?
    sql: |-
      SELECT
        country,
        COUNT(DISTINCT customer_id)
      FROM
        customer_loyalty_metrics_v
      GROUP BY
        country
      ORDER BY
        COUNT(DISTINCT customer_id) DESC NULLS LAST
    use_as_onboarding_question: false
    verified_by: Aaman Lamba
    verified_at: 1764945919
module_custom_instructions:
  sql_generation: round all numeric columns to 2 decimal points
  question_categorization: Answer all questions related to customer metrics and no other
$$
);

-- ============================================================================
-- Step 3: Verify the semantic view was created successfully
-- ============================================================================

SHOW SEMANTIC VIEWS IN SCHEMA TASTY_BYTES.HARMONIZED;

-- You should see HARMONIZEDCUSTOMERMETRICSSEMANTICVIEW in the results

-- ============================================================================
-- Step 4: Get details about the semantic view
-- ============================================================================

DESCRIBE SEMANTIC VIEW TASTY_BYTES.HARMONIZED.HARMONIZEDCUSTOMERMETRICSSEMANTICVIEW;

-- ============================================================================
-- Step 5: Grant access to other roles (optional)
-- ============================================================================

-- Grant usage to specific roles if needed
-- GRANT USAGE ON SEMANTIC VIEW TASTY_BYTES.HARMONIZED.HARMONIZEDCUSTOMERMETRICSSEMANTICVIEW 
--   TO ROLE YOUR_ROLE_NAME;

-- ============================================================================
-- Next Steps
-- ============================================================================
-- 
-- 1. Navigate to Snowsight: AI & ML → Cortex Analyst
-- 2. Create a new agent
-- 3. Add tool: Select HARMONIZEDCUSTOMERMETRICSSEMANTICVIEW
-- 4. Tool description:
--    "Use this tool to answer questions about Tasty Bytes customer loyalty 
--     program metrics, including customer demographics (name, email, phone, 
--     city, country), total sales by customer, and location visit patterns. 
--     Supports analysis of customer counts, sales revenue by geography, and 
--     customer purchasing behavior across different locations."
-- 5. Test with queries like:
--    - "How many customers are in our loyalty program?"
--    - "Which countries have the most customers?"
--    - "Show me the top 10 customers by total sales"
-- ============================================================================
